### ISSUE TITLE
inkyphat install failed to install Python library

### ISSUE THREAD

**Issue by martinohanlon** [pimoroni/inky-phat#13]
I followed the install process to install the inkyphat library but the python library (both 2 & 3) cant be imported.

Below is the result of the install script.

```
pi@pizerow2:~ $ curl https://get.pimoroni.com/inkyphat  | bash
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 38486  100 38486    0     0  77757      0 --:--:-- --:--:-- --:--:-- 77906

This script will install everything needed to use
Inky pHAT

Always be careful when running scripts and commands copied
from the internet. Ensure they are from a trusted source.

If you want to see what this script does before running it,
you should run: 'curl https://get.pimoroni.com/inkyphat'

Note: Inky pHAT requires SPI communication

Do you wish to continue? [y/N] y

Checking environment...
Updating apt indexes...
.....................

Checking hardware requirements...

Checking for packages required for GPIO control...
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
RPi.GPIO installed and up-to-date

SPI must be enabled for Inky pHAT to work
SPI is now enabled

Checking packages required by SPI interface...
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
DEPRECATION: The default format will switch to columns in the future. You can use --format=(legacy|columns) (or define a format=(legacy|columns) in your pip.conf under the [list] section) to disable this warning.
spidev installed and up-to-date

Inky pHAT comes with examples and documentation that you may wish to install.
Performing a full install will ensure those resources are installed,
along with all required dependencies. It may however take a while!

Do you wish to perform a full install? [y/N] y

Checking for dependencies...
python-numpy is already installed
python3-numpy is already installed
python-pil is already installed
python3-pil is already installed

Installing python-inkyphat...
install ok installed
Installing python3-inkyphat...
install ok installed

Checking for additional software...
python-requests is already installed
python3-requests is already installed

Downloading examples and documentation...
Resources for your Inky pHAT were copied to
/home/pi/Pimoroni/inkyphat

Finalising Install...

pi@pizerow2:~ $ cd Pimoroni/inkyphat/
pi@pizerow2:~/Pimoroni/inkyphat $ la
-bash: la: command not found
pi@pizerow2:~/Pimoroni/inkyphat $ ls
examples
pi@pizerow2:~/Pimoroni/inkyphat $ cd examples/
pi@pizerow2:~/Pimoroni/inkyphat/examples $ ls
cal-ics.py  hello.py              list-ics.py  qr.py      test.py
cal.py      InkyPhat-212x104.png  logo.py      resources  weather.py
pi@pizerow2:~/Pimoroni/inkyphat/examples $ python3 cal.py
Traceback (most recent call last):
  File "cal.py", line 10, in <module>
    import inkyphat
ImportError: No module named 'inkyphat'
pi@pizerow2:~/Pimoroni/inkyphat/examples $ python cal.py
Traceback (most recent call last):
  File "cal.py", line 10, in <module>
    import inkyphat
ImportError: No module named inkyphat
pi@pizerow2:~/Pimoroni/inkyphat/examples $

```

**Comment by martinohanlon** [comment]
Fyi - I had to install the inkyphat library with pip in order to get it to work.

```
pi@pizerow2:~/Pimoroni/inkyphat/examples $ sudo pip3 install inkyphat
Collecting inkyphat
  Downloading inkyphat-0.0.2.tar.gz (215kB)
    100% |████████████████████████████████| 225kB 171kB/s
Requirement already satisfied: spidev in /usr/lib/python3/dist-packages (from inkyphat)
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from inkyphat)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from inkyphat)
Requirement already satisfied: pillow in /usr/lib/python3/dist-packages (from inkyphat)
Building wheels for collected packages: inkyphat
  Running setup.py bdist_wheel for inkyphat ... done
  Stored in directory: /root/.cache/pip/wheels/7f/f7/48/6068987cf79cccdec468e7d6e2dac6cc7ea3b0d8726820d400
Successfully built inkyphat
Installing collected packages: inkyphat
Successfully installed inkyphat-0.0.2
pi@pizerow2:~/Pimoroni/inkyphat/examples $ python3 cal.py
Inky pHAT: Calendar

Draws a calendar for the current month to your Inky pHAT.

This example uses a sprite sheet of numbers and month names which are
composited over the background in a couple of different ways.


Shutting down display, please wait...

```

**Comment by Gadgetoid** [comment]
Curious. Just regular ol' Raspbian? Looking through the install script versus your output it looks like the deb packages should have been successfully installed.

What do you see if you run: 

```text
dpkg-query -s python-inkyphat
dpkg-query -s python3-inkyphat
```

**Comment by martinohanlon** [comment]
Interesting... dpkg suggests they were installed correctly. Python couldn't see the packages though (see below).

Regular Raspbian with Pixel installed on a Pi Zero W.  Its a few months old, so its Jessie not Stretch, but really nothing different about the build.

```
pi@pizerow2:~ $ dpkg-query -s python-inkyphat
Package: python-inkyphat
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 504
Maintainer: Phil Howard <phil@pimoroni.com>
Architecture: all
Source: inkyphat
Version: 0.0.2
Depends: python-numpy, python-pil, python-rpi.gpio, python-spidev, python:any (<< 2.8), python:any (>= 2.7.5-5~)
Suggests: python-requests
Description: python library for the Pimoroni Inky pHAT
 Ideal for name badges or displaying statutes and notifications.
 .
 This is the Python 2 version of the package.
Homepage: https://github.com/pimoroni/inky-phat
pi@pizerow2:~ $ dpkg-query -s python3-inkyphat
Package: python3-inkyphat
Status: install ok installed
Priority: extra
Section: python
Installed-Size: 504
Maintainer: Phil Howard <phil@pimoroni.com>
Architecture: all
Source: inkyphat
Version: 0.0.2
Depends: python3-numpy, python3-pil, python3-rpi.gpio, python3-spidev, python3:any (>= 3.4~)
Suggests: python3-requests
Description: python library for the Pimoroni Inky pHAT
 Ideal for name badges or displaying statutes and notifications.
 .
 This is the Python 3 version of the package.
Homepage: https://github.com/pimoroni/inky-phat
```

**Comment by martinohanlon** [comment]
Just checked again - the python library definitely cant be seen by python 2 (I only installed it for python3 using pip).

```
pi@pizerow2:~/Pimoroni/inkyphat/examples $ python cal.py
Traceback (most recent call last):
  File "cal.py", line 10, in <module>
    import inkyphat
ImportError: No module named inkyphat

```

**Comment by Gadgetoid** [comment]
I've not seen this happen before- assuming you still have this setup, what do you see if you check `python --version`?

**Comment by 4xposed** [comment]
I am having the same issue, @martinohanlon how did you solve it?
