### ISSUE TITLE
No such file: dev/i2c-1

### ISSUE THREAD

**Issue by neauoire** [pimoroni/inky-phat#28]
Trying to run examples after a fresh install, followed the instructions

```
python logo.py --type "phat" --colour "red"
```

```
Traceback (most recent call last):
  File "logo.py", line 26, in <module>
    inky_display = InkyPHAT(colour)
  File "/usr/local/lib/python2.7/dist-packages/inky/phat.py", line 27, in __init__
    v_flip=False)
  File "/usr/local/lib/python2.7/dist-packages/inky/inky.py", line 74, in __init__
    self.eeprom = eeprom.read_eeprom()
  File "/usr/local/lib/python2.7/dist-packages/inky/eeprom.py", line 103, in read_eeprom
    i2c = SMBus(1)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 253, in __init__
    self.open(bus)
  File "/usr/local/lib/python2.7/dist-packages/smbus2/smbus2.py", line 265, in open
    self.fd = os.open("/dev/i2c-{}".format(bus), os.O_RDWR)
OSError: [Errno 2] No such file or directory: '/dev/i2c-1'
```

**Comment by neauoire** [comment]
Going to `sudo raspi-config`, in `interfaces` and activating it fixes it. 
Should this be added to the documentation?
